lstm:
  n_hidden: 3
  n_neurons: 8
  learning_rate: 0.03 #3e-2
  input_shape: 1556
  dropout: 0.6
  dropout_rec: 0.6

gru:
  n_hidden: 3
  n_neurons: 8
  learning_rate: 0.03 #3e-2
  input_shape: 1556
  dropout: 0.6
  dropout_rec: 0.6

mlp:
  n_hidden: 3
  n_neurons: 128
  learning_rate: 0.003
  input_shape: 1556
  dropout: 0.6


svm:
  C:
    - 1
    - 1000
  gamma:
    - 0.0001
    - 0.001
  kernel:
    - 'rbf'
    - 'sigmoid'
  class_weight:
    - 'balanced'
    - None

cnn:
  input_shape: 1556
  n_hidden: 5
  filters:
    - 32
    - 64
#    - 128
#    - 256
  dropout: 0.6
  pool_size: 2
  pool_type: #this is not implemented yet
    - 'average'
    - 'max'
  kernel_size:
    - 1
    - 3
    - 5
#    - 11
#    - 17
  n_neurons: 128
# activation_function:
# optimizer
# stride?

rf:
  n_estimators: 100
  max_leaf_nodes: 40
  min_samples_split: 10
  bootstrap:
    - True
    - False

